import type { Metadata } from 'next';
import { Manrope, JetBrains_Mono } from 'next/font/google';
import './globals.scss';
import { Header } from '@/components/layout/Header/Header';
import { Footer } from '@/components/layout/Footer/Footer';

// TODO:
// - metadata: замінити "Create Next App" на назву й опис сайту
// - public/: видалити невикористані svg зі стартового шаблону (next, vercel, globe, file, window)
// - favicon: замінити стандартний src/app/favicon.ico на свій
// - перемикач теми (data-theme на <html>) — окремим кроком

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains_mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' className={`${manrope.variable} ${jetBrainsMono.variable}`}>
      <body>
        {/* Першим у body: з клавіатури одразу до вмісту, повз усю навігацію хедера */}
        <a href='#main-content' className='skip-link'>
          Skip to content
        </a>
        <Header />
        <main id='main-content' tabIndex={-1}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
