import type { Metadata } from 'next';
import { Manrope, JetBrains_Mono } from 'next/font/google';
import './globals.scss';

// TODO:
// - metadata: замінити "Create Next App" на назву й опис сайту
// - public/: видалити невикористані svg зі стартового шаблону (next, vercel, globe, file, window)
// - favicon: замінити стандартний src/app/favicon.ico на свій
// - .env.local з адресою API — на кроці шару API
// - перемикач теми (data-theme на <html>) — окремим кроком

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains_mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' className={`${manrope.variable} ${jetBrainsMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
